const ROUTE_PATH = Object.freeze({
  HOME: "/",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: "/product/:id",
  LOGIN: "/login",
  ACCOUNT: "/account",
  UPDATE_PROFILE: "/me/update",
  UPDATE_PASSWORD: "/password/update",
  FORGOT_PASSWORD: "/password/forgot",
  RESET_PASSWORD: "/password/reset/:token",
  CART: "/cart",
  ABOUT: "/about",
  CONTACT: "/contact",
  SIPPING: "/shipping",
  CONFIRM_ORDER: "/order/confirm",
  PROCESS_PAYMENT: "/process/payment",
  PAYMENT_SUCCESS: "/success",
  ORDERS: "/orders",
  ORDER_DETAILS: "/myorder/:id",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_NEW_PRODUCT: "/admin/product",
  ADMIN_UPDATE_PRODUCT: "/admin/product/:id",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_UPDATE_ORDER: "/admin/order/:id",
  ADMIN_USERS: "/admin/users",
  ADMIN_UPDATE_USER: "/admin/user/:id",
  ADMIN_REVIEWS: "/admin/reviews",
});

export default ROUTE_PATH;
